name: Deploy to Cloud Run

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Setup Build and Deploy
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REPO_NAME: ${{ github.event.repository.name }}
      REGION: ${{ secrets.GCP_REGION }}

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Google Cloud SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/auth@v2.1.3
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Authenticate Docker to use Google Cloud's container registry
    - name: Authenticate Docker with GCR
      run: gcloud auth configure-docker

    # Build and tag the docker image
    - name: Build and tag the docker image
      run: docker build . --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}:${{ github.sha }}

    # Push the image to GCR
    - name: Push the image to GCR
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}:${{ github.sha }}

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy "${{ github.event.repository.name }}" \
          --image "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}:${{ github.sha }}" \
          --region "${{ secrets.GCP_REGION }}" \
          --platform managed \
          --update-env-vars \
            APP_NAME=Meevil,\
            APP_ENV=production,\
            APP_KEY=${{ secrets.APP_KEY }},\
            APP_DEBUG=false,\
            APP_URL=https://meevil-838039345458.asia-southeast1.run.app,\
            DB_CONNECTION=sqlite,\
            DB_DATABASE=/app/storage/database/database.sqlite,\
            CACHE_DRIVER=file,\
            SESSION_DRIVER=file,\
            QUEUE_CONNECTION=sync,\
            LOG_CHANNEL=stack,\
            FILESYSTEM_DRIVER=local \
          --quiet
