name: Deploy to Cloud Run

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Setup Build and Deploy
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REPO_NAME: ${{ github.event.repository.name }}
      REGION: ${{ secrets.REGION }}
      GITHUB_SHA: ${{ github.sha }}

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Google Cloud SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/auth@v2.1.3
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Authenticate Docker to use Google Cloud's container registry
    - name: Authenticate Docker
      run: gcloud auth configure-docker

    # Build and push Docker image to Google Container Registry
    - name: Build and tag the docker image
      run: docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

    - name: Push the image to GCR
      run: docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

    - name: Deploy Deploy to Cloud Run
      run: gcloud run deploy $REPO_NAME --image=gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA --region=$REGION --platform=managed --quiet
